# Generated by Django 6.0.1 on 2026-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="default-product", max_length=250),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="categories.category"
            ),
        ),
    ]
