# Generated by Django 6.0.1 on 2026-02-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_slug_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="catalogue",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
