# Generated by Django 6.0.1 on 2026-03-18 13:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_catalogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_html",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
